#!/usr/bin/env zsh

# :: if awscli is not installed, then attempt to install
if ! [ -x "$(command -v aws)" ]; then
  echo "$WARN"\[hook: awscli\]"$RESET" awscli is not installed. Will install.
  echo

  if [[ "$OS" == 'linux' ]]; then
    (
      case $(uname -m) in
        x86_64) curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "$HOME/awscliv2.zip" ;;
        aarch64) curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "$HOME/awscliv2.zip" ;;
        *) echo "$WARN[hook: awscli]$RESET Unknown architecture. Aborting install." && exit 1 ;;
      esac

      mkdir -p $HOME/tmp
      unzip -d $HOME/tmp $HOME/awscliv2.zip
      sudo $HOME/tmp/aws/install
    )
  else
    curl "https://awscli.amazonaws.com/AWSCLIV2.pkg" -o "$HOME/awscliv2.pkg"
    sudo installer -pkg $HOME/awscliv2.pkg -target /
  fi
fi

# :: load AWSCLI autocompletions
autoload bashcompinit && bashcompinit
complete -C '/usr/local/bin/aws_completer' aws
