#!/usr/bin/env zsh

# :: only relevant on an OSX machine
if [[ "$OS" == 'osx' ]]; then

  # :: only run brew auto-update once daily
  export HOMEBREW_AUTO_UPDATE_SECS=86400
  export HOMEBREW_NO_ANALYTICS=1

  # :: install homebrew if it does not yet exist
  if ! [ -x "$(command -v brew)" ]; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  fi

  # :: `homebrew doctor` complains if sbin/ is not in PATH.
  export PATH="/usr/local/sbin:$PATH"
fi
