#!/usr/bin/env zsh

# :: only if dotnet is installed
export DOTNET_CLI_TELEMETRY_OUTPUT=false

# :: only if dotnet is installed
if [ -x "$(command -v dotnet)" ]; then
  export DOTNET_ROOT="$HOME/.dotnet"
  # export DOTNET_ROOT="$HOME/dev/utils/dotnet-sdk-5.0"

  export PATH="$PATH:$DOTNET_ROOT/tools"
fi
