#!/usr/bin/env zsh

# :: only if dotnet is installed
if [ -x "$(command -v dotnet)" ]; then
  # export DOTNET_ROOT="$HOME/.dotnet"
  export DOTNET_ROOT="/usr/local/share/dotnet"
  export PATH="$PATH:$DOTNET_ROOT/tools"
fi
