#!/usr/bin/env zsh

# :: only if github CLI is installed
if [ -x "$(command -v gh)" ]; then
  if gh extension list  | grep -q "gh-copilot"; then
    alias ghc='gh copilot'

    alias explain='gh copilot explain'
    alias suggest='gh copilot suggest'
  fi
fi
