#!/usr/bin/env zsh

# :: only if golang is installed
if [ -x "$(command -v go)" ]; then
  # export GOPATH=/usr/local/go
  export GOROOT=/usr/local/go
  export PATH=$PATH:$GOROOT/bin

  # :: Go v1.13+ defaults to using an upstream proxy that is managed
  #    by Google to fetch modules. This can be seen as a privacy risk.
  #
  #    The following line disables this behavior.
  #
  #    More information:
  #    https://github.com/golang/go/issues/33985
  go env -w GOPROXY=direct
fi
