#!/usr/bin/env zsh

# :: If fnm is not installed, then install
if ! [ -x "$(command -v fnm)" ]; then
  echo "$WARN"\[hook: node\]"$RESET" fnm is not installed. Will install.
  echo

  curl -fsSL https://fnm.vercel.app/install | bash
fi

eval "$(fnm env --use-on-cd)"

# :: only if yarn is installed
if [ -x "$(command -v yarn)" ]; then
  export PATH="$PATH:`yarn global bin`"
fi
