#!/usr/bin/env zsh

export PATH="$HOME/.local/share/fnm:$PATH"

# :: If fnm is not installed, then install
if ! [ -x "$(command -v fnm)" ]; then
  echo "$WARN"\[hook: node\]"$RESET" fnm is not installed. Will install.
  echo

  curl -fsSL https://fnm.vercel.app/install | bash
fi

eval "$(fnm env --use-on-cd --shell zsh)"

# :: only if yarn is installed
if [ -x "$(command -v yarn)" ]; then
  export PATH="$PATH:`yarn global bin`"
fi

# :: only if bun is installed
if [ -x "$(command -v bun)" ]; then
  # :: Bun completions
  [ -s "$HOME/.bun/_bun" ] && source "$HOME/.bun/_bun"
fi
