#!/usr/bin/env zsh

export PATH="$HOME/.rbenv/bin:$PATH"

# :: if rbenv is not installed, then attempt to install
if ! [ -x "$(command -v rbenv)" ]; then
  echo "$WARN"\[hook: rbenv\]"$RESET" rbenv is not installed. Will install.
  echo

  git clone https://github.com/rbenv/rbenv.git ~/.rbenv
fi

eval "$(rbenv init -)"
