#!/usr/bin/env zsh

export PATH="$HOME/.rbenv/bin:$PATH"

# :: if rbenv is not installed, then attempt to install
if ! [ -x "$(command -v rbenv)" ]; then
  echo "$WARN"\[hook: rbenv\]"$RESET" rbenv is not installed. Will install.
  echo

  git clone https://github.com/rbenv/rbenv.git ~/.rbenv
fi

eval "$(rbenv init - zsh)"

# :: install ruby-build if it's not available so that `rbenv install` is available to us.
if ! rbenv commands | grep install > /dev/null; then
  mkdir -p "$(rbenv root)"/plugins
  git clone https://github.com/rbenv/ruby-build.git "$(rbenv root)"/plugins/ruby-build
fi

alias be='bundle exec'

# :: create rspec aliases 
alias focus='rspec -t focus'
if [ -x "$(command -v watch)" ] && [ -x "$(command -v unbuffer)" ]; then
  alias focusw="watch -n 0.5 --color 'unbuffer rspec -t focus'"
fi

if [ -x "$(command -v forego)" ]; then
  alias fgo='forego'
  alias fgos='forego start -p 3000'
fi
