#!/usr/bin/env zsh

alias ..='cd ..'

if [ -x "$(command -v git)" ]; then
  alias g='git'
  alias d='git diff'
  alias s='git status -sb'
  alias a='git add'
  alias c='git commit -v'
  alias gb='git branch -avv'
  alias gs='git switch'
fi

if [ -x "$(command -v bat)" ]; then
  alias b='bat'
fi

if [ -x "$(command -v ddgr)" ]; then
  alias @='ddgr -n 15 --colorize -r sg-en'
  alias ddg='@'
fi

# :: ---

if [ -x "$(command -v eza)" ]; then
  # :: `eza` is cross platform.
  alias l='eza -l --group-directories-first --git --no-permissions --no-user --icons --octal-permissions --no-filesize --time-style long-iso'
  alias ll='l -a'
elif [[ "$OS" == 'linux' ]]; then
  alias l='ls -l --color --group-directories-first'
  alias ll='l -ah'
else
  if [ -x "$(command -v gls)" ]; then
    alias l='gls -l --color --group-directories-first'
    alias ll='l -ah'
  fi
fi

# :: `qrencode` is a CLI utility that encodes text into QR codes right in the shell.
if [ -x "$(command -v qrencode)" ]; then
  alias qr='qrencode --foreground FFFFFF --background 232F3E -t UTF8'
fi
