#!/usr/bin/env zsh

export VISUAL=nvim
export EDITOR=nvim

export PATH="$HOME/.local/bin:$PATH"
export FUNCTIONS_CORE_TOOLS_TELEMETRY_OPTOUT=true

# :: Attempt to detect OS
if [[ `uname` == 'Linux' ]]; then
  OS='linux'
else
  OS='osx'
fi

test -f $HOME/.prompt && source $HOME/.prompt
test -f $HOME/.aliases && source $HOME/.aliases
test -f $HOME/.functions && source $HOME/.functions
test -f $HOME/.profile.local && source $HOME/.profile.local

# :: -----------------------------------------------------------------------------------
# :: devenv specific hooks

# e.g. `hook nvm`
function hook () {
  test -f $HOME/.hooks/$@ && source $HOME/.hooks/$@
}

hook essentials
# hook iterm
hook fzf

hook brew             # :: OSX Homebrew

hook nodejs           # :: JS
hook python           # :: Python
hook ruby             # :: Ruby
hook rust             # :: Rust
# hook dotnet           # :: .NET
# hook golang           # :: Go
# hook flutter          # :: Flutter and Dart

hook awscli           # :: AWS CLI
# hook qmk              # :: QMK firmware
hook terraform        # :: Hashicorp Terraform

hook docker           # :: Docker
# hook kubernetes       # :: Kubernetes
hook vscode           # :: Visual Studio Code
hook android          # :: Android tooling

hook github           # :: Github CLI

# :: these hooks have to be after the rust hook to be safe,
#    since they fall back to using cargo
hook bat              # :: bat
hook delta            # :: git-delta

# hook isengardcli      # :: Isengard CLI
# hook builderhub       # :: BuilderHub
